version: '3'

services:

    kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: >-
          LISTENER_DOCKER_INTERNAL://kafka:19092,
          LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
        KAFKA_LISTENERS: >-
          LISTENER_DOCKER_INTERNAL://:19092,
          LISTENER_DOCKER_EXTERNAL://:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
          LISTENER_DOCKER_INTERNAL:PLAINTEXT,
          LISTENER_DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      depends_on:
        - zookeeper

    zookeeper:
      image: zookeeper
      ports:
        - "2181:2181"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper
